version: "3.7"
services:
  web:
    image: lethosor/flask-file-browser:latest
    ports:
      - "127.0.0.1:${PORT}:8000"
    restart: always
    volumes:
      - type: bind
        source: "${FILE_ROOT}"
        target: /app/files
        read_only: true
