version: "3.7"
services:
  web:
    build:
      context: .
    environment:
      - SITE_NAME
    ports:
      - "127.0.0.1:${PORT}:8000"
    restart: always
    volumes:
      - type: bind
        source: "${FILE_ROOT}"
        target: /app/files
        read_only: true
