version: "3.7"
services:
  redis:
    entrypoint: ["redis-server", "--appendonly", "yes"]
    image: redis:5-alpine
    volumes:
      - type: volume
        source: redis-data
        target: /data
  web:
    build:
      context: .
    environment:
      - SITE_NAME
    ports:
      - "127.0.0.1:${PORT}:8000"
    restart: always
    volumes:
      - type: bind
        source: "${FILE_ROOT}"
        target: /app/files
        read_only: true
volumes:
  redis-data:
